### ISSUE TITLE
PyTorch weights not relying on Pytorch Lightning

### ISSUE THREAD

**Issue by piperwolters** [utkarshmall13/CACo#3]
Would you mind sharing pytorch resnet weights (.pth files) in addition to the lightning checkpoints?

**Comment by utkarshmall13** [comment]
Hi

The pytorch weights can be found now at the path [links](https://research.cs.cornell.edu/caco/checkpoints/). You can also refer to [this new notebook](https://github.com/utkarshmall13/CACo/blob/main/notebooks/eurosat_eval_pytorch.ipynb) on how to use them.

**Comment by piperwolters** [comment]
Thank you so much!
